#!/bin/bash

# Check if an argument (IP address) is provided
if [ -z "$1" ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Store the IP address passed as an argument
IP_ADDRESS=$1

# Ping the IP address 5 times
ping -c 5 $IP_ADDRESS
